
import Image from 'next/image'
import Head from 'next/head'
import Layout from '../components/layout/Layout'
import { Children } from 'react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <h1> Hola Mundo </h1>
        </div>
      </Layout>
    </div>
  )
}
